//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Games {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Games.Form", typeof(Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        /// </summary>
        public static System.Windows.Forms.AutoSizeMode AttachBtn_AutoSizeMode {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.AutoSizeMode", resourceCulture);
                return ((System.Windows.Forms.AutoSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode AttachBtn_ImeMode {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=7}.
        /// </summary>
        public static System.Drawing.Point AttachBtn_Location {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=6,Right=4,Bottom=6}.
        /// </summary>
        public static System.Windows.Forms.Padding AttachBtn_Margin {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size AttachBtn_Size {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int AttachBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("AttachBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach .
        /// </summary>
        public static string AttachBtn_Text {
            get {
                return ResourceManager.GetString("AttachBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool BA_AutoSize {
            get {
                object obj = ResourceManager.GetObject("BA.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode BA_ImeMode {
            get {
                object obj = ResourceManager.GetObject("BA.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=108,Y=39}.
        /// </summary>
        public static System.Drawing.Point BA_Location {
            get {
                object obj = ResourceManager.GetObject("BA.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=72, Height=13}.
        /// </summary>
        public static System.Drawing.Size BA_Size {
            get {
                object obj = ResourceManager.GetObject("BA.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 43.
        /// </summary>
        public static int BA_TabIndex {
            get {
                object obj = ResourceManager.GetObject("BA.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseAddress:.
        /// </summary>
        public static string BA_Text {
            get {
                return ResourceManager.GetString("BA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=20}.
        /// </summary>
        public static System.Drawing.Point backgroundWorker1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("backgroundWorker1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        /// </summary>
        public static System.Windows.Forms.AutoSizeMode CloseBtn_AutoSizeMode {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.AutoSizeMode", resourceCulture);
                return ((System.Windows.Forms.AutoSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode CloseBtn_ImeMode {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=34}.
        /// </summary>
        public static System.Drawing.Point CloseBtn_Location {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=6,Right=4,Bottom=6}.
        /// </summary>
        public static System.Windows.Forms.Padding CloseBtn_Margin {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size CloseBtn_Size {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 35.
        /// </summary>
        public static int CloseBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CloseBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseBtn_Text {
            get {
                return ResourceManager.GetString("CloseBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Consolas, Size=10, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font fConsole_Font {
            get {
                object obj = ResourceManager.GetObject("fConsole.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=2,Y=137}.
        /// </summary>
        public static System.Drawing.Point fConsole_Location {
            get {
                object obj = ResourceManager.GetObject("fConsole.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=470, Height=200}.
        /// </summary>
        public static System.Drawing.Size fConsole_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("fConsole.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RichTextBoxScrollBars similar to Vertical.
        /// </summary>
        public static System.Windows.Forms.RichTextBoxScrollBars fConsole_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("fConsole.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=470, Height=208}.
        /// </summary>
        public static System.Drawing.Size fConsole_Size {
            get {
                object obj = ResourceManager.GetObject("fConsole.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 32.
        /// </summary>
        public static int fConsole_TabIndex {
            get {
                object obj = ResourceManager.GetObject("fConsole.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string fConsole_Text {
            get {
                return ResourceManager.GetString("fConsole.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool HealthBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("HealthBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode HealthBox_ImeMode {
            get {
                object obj = ResourceManager.GetObject("HealthBox.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=111,Y=104}.
        /// </summary>
        public static System.Drawing.Point HealthBox_Location {
            get {
                object obj = ResourceManager.GetObject("HealthBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=57, Height=17}.
        /// </summary>
        public static System.Drawing.Size HealthBox_Size {
            get {
                object obj = ResourceManager.GetObject("HealthBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 46.
        /// </summary>
        public static int HealthBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("HealthBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthBox_Text {
            get {
                return ResourceManager.GetString("HealthBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool HID_AutoSize {
            get {
                object obj = ResourceManager.GetObject("HID.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode HID_ImeMode {
            get {
                object obj = ResourceManager.GetObject("HID.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=108,Y=23}.
        /// </summary>
        public static System.Drawing.Point HID_Location {
            get {
                object obj = ResourceManager.GetObject("HID.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=13}.
        /// </summary>
        public static System.Drawing.Size HID_Size {
            get {
                object obj = ResourceManager.GetObject("HID.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 42.
        /// </summary>
        public static int HID_TabIndex {
            get {
                object obj = ResourceManager.GetObject("HID.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleID:.
        /// </summary>
        public static string HID_Text {
            get {
                return ResourceManager.GetString("HID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=25,Y=88}.
        /// </summary>
        public static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=43, Height=13}.
        /// </summary>
        public static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 40.
        /// </summary>
        public static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=7, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font label2_Font {
            get {
                object obj = ResourceManager.GetObject("label2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-1,Y=118}.
        /// </summary>
        public static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=93, Height=13}.
        /// </summary>
        public static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 51.
        /// </summary>
        public static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert=Show/Hide .
        /// </summary>
        public static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool ManaBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("ManaBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode ManaBox_ImeMode {
            get {
                object obj = ResourceManager.GetObject("ManaBox.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=111,Y=84}.
        /// </summary>
        public static System.Drawing.Point ManaBox_Location {
            get {
                object obj = ResourceManager.GetObject("ManaBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=53, Height=17}.
        /// </summary>
        public static System.Drawing.Size ManaBox_Size {
            get {
                object obj = ResourceManager.GetObject("ManaBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 45.
        /// </summary>
        public static int ManaBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ManaBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string ManaBox_Text {
            get {
                return ResourceManager.GetString("ManaBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=95,Y=-2}.
        /// </summary>
        public static System.Drawing.Point materialDivider1_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=10, Height=133}.
        /// </summary>
        public static System.Drawing.Size materialDivider1_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int materialDivider1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider1.
        /// </summary>
        public static string materialDivider1_Text {
            get {
                return ResourceManager.GetString("materialDivider1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=95,Y=55}.
        /// </summary>
        public static System.Drawing.Point materialDivider2_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=205, Height=5}.
        /// </summary>
        public static System.Drawing.Size materialDivider2_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 49.
        /// </summary>
        public static int materialDivider2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider2.
        /// </summary>
        public static string materialDivider2_Text {
            get {
                return ResourceManager.GetString("materialDivider2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-4,Y=137}.
        /// </summary>
        public static System.Drawing.Point materialDivider3_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=520, Height=2}.
        /// </summary>
        public static System.Drawing.Size materialDivider3_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int materialDivider3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider3.
        /// </summary>
        public static string materialDivider3_Text {
            get {
                return ResourceManager.GetString("materialDivider3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-4,Y=137}.
        /// </summary>
        public static System.Drawing.Point materialDivider4_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=520, Height=2}.
        /// </summary>
        public static System.Drawing.Size materialDivider4_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int materialDivider4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider4.
        /// </summary>
        public static string materialDivider4_Text {
            get {
                return ResourceManager.GetString("materialDivider4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-162,Y=129}.
        /// </summary>
        public static System.Drawing.Point materialDivider5_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=684, Height=10}.
        /// </summary>
        public static System.Drawing.Size materialDivider5_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        public static int materialDivider5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider5.
        /// </summary>
        public static string materialDivider5_Text {
            get {
                return ResourceManager.GetString("materialDivider5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-6,Y=176}.
        /// </summary>
        public static System.Drawing.Point materialDivider6_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=2, Height=180}.
        /// </summary>
        public static System.Drawing.Size materialDivider6_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 25.
        /// </summary>
        public static int materialDivider6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider6.
        /// </summary>
        public static string materialDivider6_Text {
            get {
                return ResourceManager.GetString("materialDivider6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=290,Y=-2}.
        /// </summary>
        public static System.Drawing.Point materialDivider7_Location {
            get {
                object obj = ResourceManager.GetObject("materialDivider7.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=10, Height=133}.
        /// </summary>
        public static System.Drawing.Size materialDivider7_Size {
            get {
                object obj = ResourceManager.GetObject("materialDivider7.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 50.
        /// </summary>
        public static int materialDivider7_TabIndex {
            get {
                object obj = ResourceManager.GetObject("materialDivider7.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialDivider7.
        /// </summary>
        public static string materialDivider7_Text {
            get {
                return ResourceManager.GetString("materialDivider7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OverlayBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("OverlayBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=104}.
        /// </summary>
        public static System.Drawing.Point OverlayBox_Location {
            get {
                object obj = ResourceManager.GetObject("OverlayBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=80, Height=17}.
        /// </summary>
        public static System.Drawing.Size OverlayBox_Size {
            get {
                object obj = ResourceManager.GetObject("OverlayBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 39.
        /// </summary>
        public static int OverlayBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OverlayBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OverlayBox_Text {
            get {
                return ResourceManager.GetString("OverlayBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=290,Y=-2}.
        /// </summary>
        public static System.Drawing.Point pictureBox1_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=133}.
        /// </summary>
        public static System.Drawing.Size pictureBox1_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 37.
        /// </summary>
        public static int pictureBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool procID_AutoSize {
            get {
                object obj = ResourceManager.GetObject("procID.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode procID_ImeMode {
            get {
                object obj = ResourceManager.GetObject("procID.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=108,Y=7}.
        /// </summary>
        public static System.Drawing.Point procID_Location {
            get {
                object obj = ResourceManager.GetObject("procID.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=62, Height=13}.
        /// </summary>
        public static System.Drawing.Size procID_Size {
            get {
                object obj = ResourceManager.GetObject("procID.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 41.
        /// </summary>
        public static int procID_TabIndex {
            get {
                object obj = ResourceManager.GetObject("procID.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessID: .
        /// </summary>
        public static string procID_Text {
            get {
                return ResourceManager.GetString("procID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool RageBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("RageBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode RageBox_ImeMode {
            get {
                object obj = ResourceManager.GetObject("RageBox.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=65}.
        /// </summary>
        public static System.Drawing.Point RageBox_Location {
            get {
                object obj = ResourceManager.GetObject("RageBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=52, Height=17}.
        /// </summary>
        public static System.Drawing.Size RageBox_Size {
            get {
                object obj = ResourceManager.GetObject("RageBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 47.
        /// </summary>
        public static int RageBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("RageBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage.
        /// </summary>
        public static string RageBox_Text {
            get {
                return ResourceManager.GetString("RageBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AutoSizeMode similar to GrowAndShrink.
        /// </summary>
        public static System.Windows.Forms.AutoSizeMode RestartButton_AutoSizeMode {
            get {
                object obj = ResourceManager.GetObject("RestartButton.AutoSizeMode", resourceCulture);
                return ((System.Windows.Forms.AutoSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode RestartButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("RestartButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=59}.
        /// </summary>
        public static System.Drawing.Point RestartButton_Location {
            get {
                object obj = ResourceManager.GetObject("RestartButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=6,Right=4,Bottom=6}.
        /// </summary>
        public static System.Windows.Forms.Padding RestartButton_Margin {
            get {
                object obj = ResourceManager.GetObject("RestartButton.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size RestartButton_Size {
            get {
                object obj = ResourceManager.GetObject("RestartButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 48.
        /// </summary>
        public static int RestartButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("RestartButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartButton_Text {
            get {
                return ResourceManager.GetString("RestartButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool StamBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("StamBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=111,Y=65}.
        /// </summary>
        public static System.Drawing.Point StamBox_Location {
            get {
                object obj = ResourceManager.GetObject("StamBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=17}.
        /// </summary>
        public static System.Drawing.Size StamBox_Size {
            get {
                object obj = ResourceManager.GetObject("StamBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 44.
        /// </summary>
        public static int StamBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("StamBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string StamBox_Text {
            get {
                return ResourceManager.GetString("StamBox.Text", resourceCulture);
            }
        }
    }
}
